#server:
#  port: 8001
spring:
  datasource:
    url: jdbc:postgresql://db:5432/md_db
    username: ash
    password: D28z6eqMxIlVX2rgycFRTXQ2TDE6pYFG


  
  #    こちらはローカル環境でダイレクトに入れる環境
  #spring:
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/${DB_NAME}
  #    username: ${DB_USER}
  #    password: ${DB_PASS}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql



#  こちらはAWSでデプロイする環境
#    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
#    username: ${RDS_USERNAME}
#    password: ${RDS_PASSWORD}

#   こちらはローカル環境でダイレクトに入れる環境



config:
  import: optional:file:.env[.properties]

logging:
  level:
    org.springframework.security: ERROR
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG


mybatis:
  configuration:
    #   アンダースコアをキャメルケースに変換OK（マッピング
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
