#server:
#  port: 5000
spring:
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
#    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
#    username: ${RDS_USERNAME}
#    password: ${RDS_PASSWORD}
  sql:
    init:
      mode: always

  config:
    import: optional:file:.env[.properties]

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG


mybatis:
  configuration:
    #   アンダースコアをキャメルケースに変換OK（マッピング
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
