#server:
#  port: 8002
spring:
  datasource:
    url: jdbc:postgresql://dpg-d01rekje5dus73bgedj0-a:5432/md_db_wduc_dic8
    username: ash
    password: txVTxp7MbcGOV5rAZQlemp5NFNEMW5hr



  #      こちらはローカル環境でダイレクトに入れる環境
  #spring:
  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/md_db_wduc
  #    username: postgres
  #    password: porigone
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql



#  こちらはAWSでデプロイする環境
#    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
#    username: ${RDS_USERNAME}
#    password: ${RDS_PASSWORD}

#   こちらはローカル環境でダイレクトに入れる環境



#config:
#  import: optional:file:.env[.properties]

logging:
  level:
    org.springframework.security: ERROR
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
    org.apache.ibatis: DEBUG


mybatis:
  configuration:
    #   アンダースコアをキャメルケースに変換OK（マッピング
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
