server:
  port: 8002
#spring:
#  datasource:
#    url: jdbc:postgresql://dpg-d001rt9r0fns73drbadg-a:5432/md_db_wduc
#    username: ash
#    password: D28z6eqMxIlVX2rgycFRTXQ2TDE6pYFG



#      こちらはローカル環境でダイレクトに入れる環境
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
sql:
  init:
    mode: always
    schema-locations: classpath:schema.sql
    data-locations: classpath:data.sql



#  こちらはAWSでデプロイする環境
#    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
#    username: ${RDS_USERNAME}
#    password: ${RDS_PASSWORD}

#   こちらはローカル環境でダイレクトに入れる環境



config:
  import: optional:file:.env[.properties]

logging:
  level:
    org.springframework.security: ERROR
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
    org.apache.ibatis: DEBUG


mybatis:
  configuration:
    #   アンダースコアをキャメルケースに変換OK（マッピング
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
